package com.utec.inventario.domain;

public enum AccionAuditoria {
    CREAR, EDITAR, ACTIVAR, DESACTIVAR, CAMBIAR_ROL, RESTABLECER_CONTRASENA,
    ASIGNAR_LABORATORIOS, TRASLADAR, INICIAR_MANTENIMIENTO,
    COMPLETAR_MANTENIMIENTO, CANCELAR_MANTENIMIENTO
}

